---
# Example T9 config file
# `cp example-config.yaml config.yaml` to get started
# Keep this file unchanged for a constant reference
# Delete this comment in your conifg.yaml

# This config works as-is in the supplied docker-compose environment.
# In other environments, you will need to update operational configs like hosts, ports, credentials,
# and filesystem paths. Nicks, channel names, etc. may need to change if you do not own the IRC server.


# required connection info
host: 'irc'
port: 6667
nick: 'T9'
user: 'T9'
vhost: 'dot'
realname: 'T9 Anything Bot'
tls: False

# optional connection password (most servers dont use these)
#password: ''

# optional TLS configs
# Note: default system CA certs always included for verifications
#
#tls_verify: True
#
# A single PEM file containing one or more CA certs for verification
#tls_ca_file: '/opt/my_deployments/ssl/internal_ca.pem'
#
# The CA directory has a very specific filename format required by OpenSSL
# Using this is not recommended if you're not familiar with the format
#tls_ca_directory: '/opt/my_deployments/ssl/ca_certs'

# optional TLS client certificate configs
#tls_client_cert: '/opt/my_deployments/t9/irc_cert.pem'
#tls_client_private_key: '/opt/my_deployments/t9/irc_key.pem'

# required - URL for the T9 exec server endpoint
exec_server_base_url: 'http://t9-exec-server:8080'

# optional- customize log output channel, defaults to #{nick}-console
# Must start with #{nick}- if commands, etc. are to work normally in this channel
#console_channel: '#T9-console'

# optional logging level name to use for the irc handler
# defaults to info, set to False to disable irc logging
console_channel_level: INFO

# optional initial list of channels
# invited channels will be persisted in the db if configured
channels:
  - '#general'
  - '#T9-playground'

# required string to return for help commands
help: "https://github.com/ashafer01/T9/wiki/T9-User-Docs"

# required leader characters for various purposes, can specify multiple
# equivalent options
primitive_leaders: '$'
command_leaders: '$'
user_leaders: '!.;'

# optional pastebin function that accepts a single string as an argument
# and returns a web URL showing the full string ideally in monospace font
# This is used to capture stderr output from user functions. If this config
# is not set only the final line of stderr output will be logged
#pastebin_function: my_paste.paster_module.paste_text_function

# optional configs to enable accepting files over DCC and making them
# available on the container
dcc_max_size: 10485760
dcc_dir: '/media/t9-home-mnt/user'

# optional secure base directory configs to enable write-locking commands
# works together with secrets manager
secure_base: '/home/user/secure'

# db is optional but some features will not work without one
# keys passed through as keywords to psycopg2.connect()
# designed for Postgres and psycopg2
db:
  user: 'postgres'
  dbname: 'postgres'
  password: 'password'
  host: 'postgres'

# optionally enable passing in T9_DB_ environment variables to $exec calls
# allows arbitrary keys below user_db
# keys will be lowercased and added to T9_DB_DSN as space-separated key=value pairs (if no `dsn` key is defined)
# additionally, keys will be uppercased and defined as individual T9_DB_ variables for exec calls
# designed for Postgres
user_db:
  user: 't9_exec'
  dbname: 'some_data'
  host: 'postgres'
  port: 5432


# security options - all optional configs

# completely ignore all messages from these nicknames
ignore:
  - 'spambot'
  - 'spamperson'

# whitelist of nicknames allowed to invite
# set to False to disable invites entirely
#invite_allowed: False

# open to everyone with empty whitelist (or no config)
invite_allowed: []

# only allow function definitions in T9 channels
define_functions_in_t9_channels_only: False


# exec limits - all optional configs

# unchangeable maximum exec time for user functions
function_exec_time: '10s'

# default max exec time for the $exec command, changeable with $exec -t
default_exec_time: '10s'

# maximum acceptable value for $exec -t
max_exec_time: '2h'

# sets this value to LC_ALL and LANG for $exec runs
exec_locale: 'en_US.UTF-8'

# enable extra python utf8 env vars for $exec runs
exec_python_utf8: True

# maximum user function call depth
stack_limit: 4


# optional logging config
# standard python logging dict config
# https://docs.python.org/3/library/logging.config.html#logging-config-dictschema

logging:
  version: 1
  formatters:
    console:
      format: '[%(asctime)s] %(name)s %(levelname)s : %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: console
  loggers:
    T9:  # logger name must match the configured `nick`
      level: DEBUG
      handlers: [console]
